kind: Service
apiVersion: v1
metadata:
  name: postgresql-1-1
spec:
  selector:
    name: postgres-1-1
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: LoadBalancer
  loadBalancerIP: 192.168.216.110 

