apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-1
    group: kb-mb-wl
  name: web-service-l2
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: addresspool-l2
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-2
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-server-l2
  type: LoadBalancer
  externalTrafficPolicy: Local

