apiVersion: v1
kind: Pod
metadata:
  name: uperf-server-ci
  labels:
    app: uperf-server-ci
spec:
  containers:
  - name: app
    image: quay.io/cloud-bulldozer/uperf:latest
    command: ["/bin/sh","-c"]
    args: ["uperf -s -v -P 20000"]
  resources:
      limits:
        memory: "10Gi"
        cpu: "5000m"
  securityContext:
    privileged: true
    sysctls:
    - name: net.ipv4.ip_local_port_range
      value: 20000 20011
  nodeSelector:
    kubernetes.io/hostname: worker001-5039ms
