apiVersion: v1
kind: Service
metadata:
  name: uperf-service-lb
  annotations:
    metallb.universe.tf/address-pool: addresspool-l2
spec:
  ports:
  - name: uperf
    port: 30000
    protocol: TCP
    targetPort: 30000
  - name: uperf-1
    port: 30001
    protocol: UDP
    targetPort: 30001
  selector:
    app: uperf-server-1
  type: LoadBalancer
