apiVersion: v1
kind: Service
metadata:
  name: uperf-service-ci
spec:
  ports:
  - name: uperf-3
    port: 20000
    protocol: UDP
    targetport: 20000
  - name: uperf-4
    port: 20001
    protocol: UDP
    targetport: 20001
  - name: uperf-5
    port: 20002
    protocol: UDP
    targetport: 20002
  selector:
    app: uperf-server-ci
