apiVersion: v1
kind: Pod
metadata:
  name: uperf
  labels:
    app: uperf-server-1
spec:
  containers:
  - name: app
    image: quay.io/cloud-bulldozer/uperf:latest
    command: ["/bin/sh","-c"]
    args: ["uperf -s -v -P 30000"]
  resources:
      limits:
        memory: "10Gi"
        cpu: "5000m"
  securityContext:
    privileged: true
