apiVersion: v1
kind: Pod
metadata:
  name: uperf-pod-server
  labels:
    app: uperf-server
spec:
  containers:
  - name: app
    image: quay.io/cloud-bulldozer/uperf:latest
    command: ["/bin/sh","-c"]
    args: ["uperf -s -v -P 30000"]
  securityContext:
    privileged: true
    sysctls:
    - name: net.ipv4.ip_local_port_range
      value: 30000 30011
  nodeSelector:
    kubernetes.io/hostname: worker001-5039ms
