---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: curl-{{.Iteration}}-{{.Replica}}
spec:
  selector:
    matchLabels:
      app: curl-{{.Iteration}}-{{.Replica}}
  template:
    metadata:
      labels:
        app: curl-{{.Iteration}}-{{.Replica}}
    spec:
      nodeSelector: {{.nodeSelector}}
      containers:
      - name: curl 
        image: quay.io/cloud-bulldozer/curl:latest
        command: ["sleep", "inf"]
        env:
        - name: WEBSERVER_HOSTNAME
          value: {{.name}}-{{.Iteration}}-{{.Replica}}
        - name: WEBSERVER_PORT
          value: "8080"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        readinessProbe:
          exec:
            command: 
              - "/bin/sh"
              - "-c"
              - "curl ${WEBSERVER_HOSTNAME}:${WEBSERVER_PORT}"
          periodSeconds: 1
      restartPolicy: Always
