---
kind: Service
apiVersion: v1
metadata:
  name: {{.name}}-{{.Iteration}}-{{.Replica}}
  annotations:
    metallb.universe.tf/address-pool: addresspool-l3
spec:
  selector:
    app: {{.name}}-{{.Iteration}}-{{.Replica}}
  ports:
  - name: {{.name}}
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
